name: CI-CD

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  TF_WORKING_DIR: infra/terraform
  GHCR_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # делаем outputs, чтобы terraform-job мог взять теги образов
    outputs:
      producer: ${{ steps.images.outputs.producer }}
      fraud: ${{ steps.images.outputs.fraud }}
      payment: ${{ steps.images.outputs.payment }}
      analytics: ${{ steps.images.outputs.analytics }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      # Function to lowercase the repo
      # -----------------------------
      - name: Lowercase repo name
        id: repo
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build & push order-producer image
        uses: docker/build-push-action@v6
        with:
          context: ./producer
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.repo_lower }}/order-producer:latest

      - name: Build & push fraud-service image
        uses: docker/build-push-action@v6
        with:
          context: ./consumers/fraud-service
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.repo_lower }}/fraud-service:latest

      - name: Build & push payment-service image
        uses: docker/build-push-action@v6
        with:
          context: ./consumers/payment-service
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.repo_lower }}/payment-service:latest

      - name: Build & push analytics-service image
        uses: docker/build-push-action@v6
        with:
          context: ./consumers/analytics-service
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ steps.repo.outputs.repo_lower }}/analytics-service:latest

      - name: Export image tags
        id: images
        run: |
          REPO="${{ steps.repo.outputs.repo_lower }}"
          echo "producer=ghcr.io/$REPO/order-producer:latest" >> $GITHUB_OUTPUT
          echo "fraud=ghcr.io/$REPO/fraud-service:latest" >> $GITHUB_OUTPUT
          echo "payment=ghcr.io/$REPO/payment-service:latest" >> $GITHUB_OUTPUT
          echo "analytics=ghcr.io/$REPO/analytics-service:latest" >> $GITHUB_OUTPUT

  terraform:
    needs: build-and-push
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        env:
          TF_VAR_container_image_producer: ${{ needs.build-and-push.outputs.producer }}
          TF_VAR_container_image_fraud: ${{ needs.build-and-push.outputs.fraud }}
          TF_VAR_container_image_payment: ${{ needs.build-and-push.outputs.payment }}
          TF_VAR_container_image_analytics: ${{ needs.build-and-push.outputs.analytics }}
          TF_VAR_confluent_api_key: ${{ secrets.CONFLUENT_API_KEY }}
          TF_VAR_confluent_api_secret: ${{ secrets.CONFLUENT_API_SECRET }}
          TF_VAR_confluent_bootstrap_servers: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        env:
          TF_VAR_container_image_producer: ${{ needs.build-and-push.outputs.producer }}
          TF_VAR_container_image_fraud: ${{ needs.build-and-push.outputs.fraud }}
          TF_VAR_container_image_payment: ${{ needs.build-and-push.outputs.payment }}
          TF_VAR_container_image_analytics: ${{ needs.build-and-push.outputs.analytics }}
          TF_VAR_confluent_api_key: ${{ secrets.CONFLUENT_API_KEY }}
          TF_VAR_confluent_api_secret: ${{ secrets.CONFLUENT_API_SECRET }}
          TF_VAR_confluent_bootstrap_servers: ${{ secrets.CONFLUENT_BOOTSTRAP_SERVERS }}
        run: terraform apply -auto-approve tfplan
